import { getLetter, getSpecial } from './keyboardHelpers.js';

export const KEY_CODES = {
  //
  Backquote: getLetter('ё', 'Ё', '`', '~', [], true),
  Digit1: getLetter('1', '!', '1', '!'),
  Digit2: getLetter('2', "'", '2', '@'),
  Digit3: getLetter('3', '№', '3', '#'),
  Digit4: getLetter('4', ';', '4', '$'),
  Digit5: getLetter('5', '%', '5', '%'),
  Digit6: getLetter('6', ':', '6', '^'),
  Digit7: getLetter('7', '?', '7', '&'),
  Digit8: getLetter('8', '*', '8', '*'),
  Digit9: getLetter('9', '(', '9', '('),
  Digit0: getLetter('0', ')', '0', ')'),
  Minus: getLetter('-', '_', '-', '_'),
  Equal: getLetter('=', '+', '=', '+'),
  Backspace: getSpecial('Backspace', ['key_flex']),
  //
  Tab: getSpecial('Tab', ['key_tab', 'key_flex'], '\t'),
  KeyQ: getLetter('й', 'Й', 'q', 'Q'),
  KeyW: getLetter('ц', 'Ц', 'w', 'W'),
  KeyE: getLetter('у', 'У', 'e', 'E'),
  KeyR: getLetter('к', 'К', 'r', 'R'),
  KeyT: getLetter('е', 'Е', 't', 'T'),
  KeyY: getLetter('н', 'Н', 'y', 'Y'),
  KeyU: getLetter('г', 'Г', 'u', 'U'),
  KeyI: getLetter('ш', 'Ш', 'i', 'I'),
  KeyO: getLetter('щ', 'Щ', 'o', 'O'),
  KeyP: getLetter('з', 'З', 'p', 'P'),
  BracketLeft: getLetter('х', 'Х', '[', '{'),
  BracketRight: getLetter('ъ', 'Ъ', ']', '}'),
  Backslash: getLetter('\\', '/', '\\', '|'),
  Delete: getSpecial('Del', ['key_flex']),
  //
  CapsLock: getSpecial('CapsLock', ['key__capslock', 'key_flex']),
  KeyA: getLetter('ф', 'Ф', 'a', 'A'),
  KeyS: getLetter('ы', 'Ы', 's', 'S'),
  KeyD: getLetter('в', 'В', 'd', 'D'),
  KeyF: getLetter('а', 'А', 'f', 'F'),
  KeyG: getLetter('п', 'П', 'g', 'G'),
  KeyH: getLetter('р', 'Р', 'h', 'H'),
  KeyJ: getLetter('о', 'О', 'j', 'J'),
  KeyK: getLetter('л', 'Л', 'k', 'K'),
  KeyL: getLetter('д', 'Д', 'l', 'L'),
  Semicolon: getLetter('ж', 'Ж', ';', ':'),
  Quote: getLetter('э', 'Э', "'", '"'),
  Enter: getSpecial('Enter', ['key_flex'], '\n'),
  //
  ShiftLeft: getSpecial('Shift', ['key_flex']),
  KeyZ: getLetter('я', 'Я', 'z', 'Z'),
  KeyX: getLetter('ч', 'Ч', 'x', 'X'),
  KeyC: getLetter('с', 'С', 'c', 'C'),
  KeyV: getLetter('м', 'М', 'v', 'V'),
  KeyB: getLetter('и', 'И', 'b', 'B'),
  KeyN: getLetter('т', 'Т', 'n', 'N'),
  KeyM: getLetter('ь', 'Ь', 'm', 'M'),
  Comma: getLetter('б', 'Б', ',', '<'),
  Period: getLetter('ю', 'Ю', '.', '>'),
  Slash: getLetter('.', ',', '/', '?'),
  ArrowUp: getLetter('⇧', '⇧', '⇧', '⇧'),
  ShiftRight: getSpecial('Shift', ['key_flex']),
  //
  ControlLeft: getSpecial('Ctrl', ['key_flex']),
  MetaLeft: getSpecial('Win', ['key_flex'], 'WIN'),
  AltLeft: getSpecial('Alt', [], 'ALT'),
  Space: getSpecial('Space', ['key_space'], ' '),
  AltRight: getSpecial('Alt', ['key_flex'], 'ALT'),
  ArrowLeft: getLetter('⇦', '⇦', '⇦', '⇦'),
  ArrowDown: getLetter('⇩', '⇩', '⇩', '⇩'),
  ArrowRight: getLetter('⇨', '⇨', '⇨', '⇨'),
  ControlRight: getSpecial('Ctrl', []),
};

export const KEYBOARD_MAP = [
  [ // line 1
    'Backquote',
    'Digit1',
    'Digit2',
    'Digit3',
    'Digit4',
    'Digit5',
    'Digit6',
    'Digit7',
    'Digit8',
    'Digit9',
    'Digit0',
    'Minus',
    'Equal',
    'Backspace',
  ],
  [// line 2
    'Tab',
    'KeyQ',
    'KeyW',
    'KeyE',
    'KeyR',
    'KeyT',
    'KeyY',
    'KeyU',
    'KeyI',
    'KeyO',
    'KeyP',
    'BracketLeft',
    'BracketRight',
    'Backslash',
    'Delete',
  ],
  [// line 3
    'CapsLock',
    'KeyA',
    'KeyS',
    'KeyD',
    'KeyF',
    'KeyG',
    'KeyH',
    'KeyJ',
    'KeyK',
    'KeyL',
    'Semicolon',
    'Quote',
    'Enter',
  ],
  [// line 4
    'ShiftLeft',
    'KeyZ',
    'KeyX',
    'KeyC',
    'KeyV',
    'KeyB',
    'KeyN',
    'KeyM',
    'Comma',
    'Period',
    'Slash',
    'ArrowUp',
    'ShiftRight',
  ],
  [// line 5
    'ControlLeft',
    'MetaLeft',
    'AltLeft',
    'Space',
    'AltRight',
    'ArrowLeft',
    'ArrowDown',
    'ArrowRight',
    'ControlRight',
  ],
];
